import { PHASE_LABELS, type DeploymentPlan } from '../../../engine/deploymentPlan';
import type { Design } from '../../../model/types';
import { fmtLong, overallDone, titleLookup, toIsoDate, type Schedule } from './planUtils';

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** Markdown export — same structure as the original Architecture Designer, plus a schedule table. */
export function buildPlanMarkdown(plan: DeploymentPlan, schedule: Schedule, design: Design): string {
  const ps = plan.projectSummary;
  const { categoryParties, checkedSteps, optimistic } = design.plan;
  const title = titleLookup(plan);
  const done = overallDone(plan, checkedSteps);

  let md = `# Cribl Deployment Plan\n\n`;
  if (design.name) md += `**Design:** ${design.name}${design.customer ? ` (${design.customer})` : ''}\n`;
  md += `**Mode:** ${ps.mode}\n`;
  md += `**Deployment Model:** ${ps.deploymentModel}\n`;
  md += `**Total Inbound:** ${ps.totalInboundGB.toFixed(0)} GB/day | **Total Outbound:** ${ps.totalOutboundGB.toFixed(0)} GB/day\n`;
  md += `**Worker Nodes:** ${ps.totalNodes} deployed (${ps.nodesForCapacity} for capacity + HA spares) across ${ps.workerGroups} Worker Group(s)\n`;
  if (ps.totalEdgeNodes > 0) md += `**Edge Nodes:** ${ps.totalEdgeNodes.toLocaleString()}\n`;
  md += `**Sources:** ${ps.sourceCount} | **Destinations:** ${ps.destinationCount}\n`;
  md += `**Estimated Timeline:** ${plan.totalEstimatedDays.min}-${plan.totalEstimatedDays.max} days (sequential)\n`;
  md += `**Scheduled Timeline:** ${schedule.totalDays} days (${optimistic ? 'optimistic' : 'conservative'}, parallel), ${fmtLong(schedule.start)} → ${fmtLong(schedule.end)}\n`;
  md += `**Progress:** ${done}/${plan.totalSteps} steps complete\n\n`;

  const hasParties = plan.categories.some((c) => (categoryParties[c.categoryId] ?? []).length > 0);
  md += `## Schedule\n\n`;
  md += `| # | Category | Phase | Start | End | Days | Critical path | Depends on |${hasParties ? ' Assigned To |' : ''}\n`;
  md += `|---|---|---|---|---|---|---|---|${hasParties ? '---|' : ''}\n`;
  schedule.scheduled.forEach((s, i) => {
    const deps = s.dependencies.map(title).join(', ') || '—';
    const assigned = (categoryParties[s.categoryId] ?? []).join(', ') || '—';
    md += `| ${i + 1} | ${cell(s.title)} | ${PHASE_LABELS[s.phase]} | ${toIsoDate(s.startDate)} | ${toIsoDate(s.endDate)} | ${s.duration} | ${s.critical ? 'Yes' : ''} | ${cell(deps)} |${hasParties ? ` ${cell(assigned)} |` : ''}\n`;
  });
  md += `\n---\n\n`;

  plan.categories.forEach((cat, catIdx) => {
    md += `## ${catIdx + 1}. ${cat.title}\n\n`;
    const assigned = categoryParties[cat.categoryId] ?? [];
    if (assigned.length > 0) md += `**Assigned To:** ${assigned.join(', ')}\n\n`;
    md += `**Phase:** ${PHASE_LABELS[cat.phase]} | **Est:** ${
      cat.effort ? `${cat.effort.days} days (from ${Math.round(cat.effort.hours * 100) / 100} h effort on ${cat.effort.stepsWithEffort}/${cat.steps.length} steps)` : `${cat.estimatedDays.min}-${cat.estimatedDays.max} days`
    }`;
    if (cat.dependencies.length > 0) md += ` | **Depends on:** ${cat.dependencies.map(title).join(', ')}`;
    md += `\n\n`;
    md += `> ${cat.summary}\n\n`;

    cat.steps.forEach((step, stepIdx) => {
      md += `### ${catIdx + 1}.${stepIdx + 1} ${step.title}\n\n`;
      if (checkedSteps[step.id]) md += `**Status:** Done\n\n`;
      md += `${step.detail}\n\n`;
      if (step.owner) md += `**Owner:** ${step.owner}\n\n`;
      const eff = design.plan.stepEffort?.[step.id];
      if (eff && eff.value > 0) md += `**Effort:** ${eff.value} ${eff.unit === 'min' ? 'min' : 'h'}\n\n`;
      md += `**Technical Details:**\n\`\`\`\n${step.technical}\n\`\`\`\n\n`;
    });
    md += `---\n\n`;
  });

  md += `_Generated by ArMo - Cribl Architecture Designer on ${fmtLong(new Date())}_\n`;
  return md;
}
